name: 'Trigger Open PR Workflows'
description: 'Triggers workflows for all open pull requests when changes are pushed to the main branch.'
author: 'Debuide org'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  base-branch:
    description: 'Name of the base branch to check and trigger PR workflows from'
    required: false
    default: 'main'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'git-pull-request'
  color: 'blue' 