name: 'Notify PRs'
description: 'Triggers workflows for all open pull requests when changes are pushed to the base branch.'
author: 'Your Name'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  base-branch:
    description: 'Name of the base branch to check'
    required: false
    default: 'main'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'git-pull-request'
  color: 'green' 