name: 'PR Workflow Rerunner'
description: 'Triggers workflow reruns for open PRs'
author: 'Your Name'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'refresh-cw'
  color: 'blue'

outputs:
  rerun-count:
    description: 'Number of PR workflows that were rerun'
  rerun-status:
    description: 'Status of the rerun operation (success/failure)' 