name: 'Main Branch Status Check'
description: 'Checks if the main branch is green before allowing PR to proceed. Designed for pull_request events.'
author: 'Your Name'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  main-branch:
    description: 'Name of the main branch to check'
    required: false
    default: 'main'

runs:
  using: "composite"
  steps:
    - name: Check Main Branch Status
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        BRANCH: ${{ inputs.main-branch }}
      run: |
        # Get the latest commit status on main branch
        STATUS=$(gh api \
          -H "Accept: application/vnd.github+json" \
          /repos/${{ github.repository }}/commits/$BRANCH/status \
          --jq '.state')
        
        echo "Main branch status: $STATUS"
        
        if [ "$STATUS" != "success" ]; then
          echo "::error::⛔ Cannot proceed: $BRANCH branch is RED (status: $STATUS)"
          exit 1
        fi
        
        echo "✅ $BRANCH branch is GREEN"

branding:
  icon: 'git-pull-request'
  color: 'green' 