name: Trigger PR Workflows

on:
  push:
    branches: [ main ]  # Adjust this to match the base branch you want to monitor

jobs:
  trigger-pr-workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Trigger Open PR Workflows
        uses: ./  # Uses the local action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-branch: 'main'  # This should match the branch you want to monitor