name: PR Check

on:
  pull_request:
    branches: [ main ]  # Only run when PRs are targeting main branch

jobs:
  check-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Main Branch Status
        uses: ./  # Uses the local action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          main-branch: 'main' 