name: Test Action

on:
  pull_request:
    branches:
      - main
      - develop
      - release/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Check Base Branch Status
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-branch: 'main'  # Explicitly specify the base branch 